name: campo_minado
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/aberto_0.jpeg
    - assets/images/aberto_1.jpeg
    - assets/images/aberto_2.jpeg
    - assets/images/aberto_3.jpeg
    - assets/images/aberto_4.jpeg
    - assets/images/aberto_5.jpeg
    - assets/images/aberto_6.jpeg
    - assets/images/aberto_7.jpeg
    - assets/images/aberto_8.jpeg
    - assets/images/bandeira.jpeg
    - assets/images/bomba_0.jpeg
    - assets/images/bomba_1.jpeg
    - assets/images/fechado.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
